- name: add-apt-repostory is installed
  become: yes
  apt: name=software-properties-common state=latest

- name: Oracle Java Repository is added
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa'

- name: OpenJDK 11 is installed
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - openjdk-11-jdk
    - ca-certificates



#  2 recipe
#  sudo add-apt-repository ppa:linuxuprising/java
#  sudo apt-get update
#  sudo apt-get install oracle-java11-installer-local
