- name: Hosts are defined
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]

- name: jq is installed
  apt:
    name: jq
    force: yes
  tags: [common]

- name: htop is installed
  apt:
    name: htop
    force: yes
  tags: [common]
