# based-on DevOps toolkit 2.0

- name: Docker repository is added and apt-cache updated
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ debian_version }} main
    update_cache: yes
    state: present
  tags: [docker]

- name: Docker is installed
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: python-pip is installed
  apt:
    name: python-pip
    state: present
    force: yes
  tags: [docker]

- name: docker-py is installed
  pip:
    name: docker-py
    version: 1.10.6
    state: present
  tags: [docker]

- name: Config files are present
  template:
    src: "{{ docker_cfg }}"
    dest: "{{ docker_cfg_dest }}"
  register: copy_result
  tags: [docker]

- name: systemctl Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_result|changed and is_systemd is defined
  tags: [docker]

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result
  tags: [docker]

- name: Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
  tags: [docker]
